package main

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"strings"
	"testing"
)

// The files under frontend/wailsjs are GENERATED by `wails build`, but they are
// also committed and imported by the frontend. A hand-edit that drifts from the
// Go side rots silently: the TypeScript still compiles, and the call only fails
// at runtime inside the desktop shell. These tests derive the expectation from
// the Go types by reflection, so drift fails the build instead.

const (
	appJSPath     = "frontend/wailsjs/go/main/App.js"
	appDTSPath    = "frontend/wailsjs/go/main/App.d.ts"
	appModelsPath = "frontend/wailsjs/go/models.ts"
)

// exportedAppMethods returns the method names Wails binds for *App: every
// exported method. Unexported ones (startup, watchClipboard, …) are not bound.
func exportedAppMethods() []string {
	t := reflect.TypeOf(NewApp())
	var names []string
	for i := 0; i < t.NumMethod(); i++ {
		names = append(names, t.Method(i).Name)
	}
	return names
}

func readRepoFile(t *testing.T, rel string) string {
	t.Helper()
	body, err := os.ReadFile(rel)
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(body)
}

// Every bound method must have a binding, and no binding may name a method that
// no longer exists.
func TestGeneratedBindingsMatchExportedAppMethods(t *testing.T) {
	js := readRepoFile(t, appJSPath)
	dts := readRepoFile(t, appDTSPath)
	methods := exportedAppMethods()

	if len(methods) == 0 {
		t.Fatal("reflection found no exported methods on *App")
	}

	for _, name := range methods {
		if !strings.Contains(js, "export function "+name+"(") {
			t.Errorf("%s is bound by Wails but missing from %s", name, appJSPath)
		}
		if !strings.Contains(js, fmt.Sprintf(`window['go']['main']['App']['%s']`, name)) {
			t.Errorf("%s in %s does not dispatch to the matching Go binding", name, appJSPath)
		}
		if !strings.Contains(dts, "export function "+name+"(") {
			t.Errorf("%s is bound by Wails but missing from %s", name, appDTSPath)
		}
	}

	// The reverse direction: a stale declaration for a method that was removed.
	known := map[string]bool{}
	for _, n := range methods {
		known[n] = true
	}
	for _, line := range strings.Split(dts, "\n") {
		const prefix = "export function "
		idx := strings.Index(line, prefix)
		if idx < 0 {
			continue
		}
		name := line[idx+len(prefix):]
		if p := strings.Index(name, "("); p >= 0 {
			name = name[:p]
		}
		if !known[name] {
			t.Errorf("%s declares %q, which is not an exported method on *App", appDTSPath, name)
		}
	}
}

// ChooseDir returns (string, error) and Capabilities returns a struct — the
// declared TypeScript return types must match, since a wrong one is invisible
// until it blows up at runtime.
func TestGeneratedBindingReturnTypes(t *testing.T) {
	dts := readRepoFile(t, appDTSPath)
	for _, want := range []string{
		"export function ChooseDir():Promise<string>;",
		"export function GetApiBase():Promise<string>;",
		"export function Capabilities():Promise<main.DesktopCapabilities>;",
	} {
		if !strings.Contains(dts, want) {
			t.Errorf("%s is missing the declaration %q", appDTSPath, want)
		}
	}
	// The struct return type has to be imported for the declaration to compile.
	if !strings.Contains(dts, `import {main} from '../models';`) {
		t.Errorf("%s does not import the models namespace it references", appDTSPath)
	}
}

// models.ts must carry exactly the JSON field names DesktopCapabilities
// marshals to — a renamed tag with a stale model is a silently undefined field.
func TestModelsMatchDesktopCapabilitiesJSONTags(t *testing.T) {
	models := readRepoFile(t, appModelsPath)

	encoded, err := json.Marshal(DesktopCapabilities{})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	var fields map[string]any
	if err := json.Unmarshal(encoded, &fields); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if len(fields) == 0 {
		t.Fatal("DesktopCapabilities marshalled to no fields")
	}

	if !strings.Contains(models, "export class DesktopCapabilities {") {
		t.Fatalf("%s does not declare DesktopCapabilities", appModelsPath)
	}
	for name := range fields {
		if !strings.Contains(models, name+":") {
			t.Errorf("%s is missing field %q from the Go json tags", appModelsPath, name)
		}
		if !strings.Contains(models, fmt.Sprintf(`source["%s"]`, name)) {
			t.Errorf("%s does not read %q in its constructor", appModelsPath, name)
		}
	}

	// And the reverse: a field in the model that Go no longer emits.
	for _, line := range strings.Split(models, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "this.") || !strings.Contains(line, "source[") {
			continue
		}
		start := strings.Index(line, `source["`) + len(`source["`)
		end := strings.Index(line[start:], `"`)
		if end < 0 {
			continue
		}
		name := line[start : start+end]
		if _, ok := fields[name]; !ok {
			t.Errorf("%s reads %q, which DesktopCapabilities no longer marshals", appModelsPath, name)
		}
	}
}
