// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDir() {
  return window['go']['main']['App']['ChooseDir']();
}

export function GetApiBase() {
  return window['go']['main']['App']['GetApiBase']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
