// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDir():Promise<string>;

export function GetApiBase():Promise<string>;

export function Greet(arg1:string):Promise<string>;
